### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by tokuno-astron** [evbauer/MESA-Docker#14]
Hi, I got queer error message after I launch 
`./win_home_dockerMESA.sh | tee launch.txt`
after run
`export MACHINE_STORAGE_PATH=C:\\docker`
`docker-machine rm mesa-machine`.

[launch.txt](https://github.com/evbauer/MESA-Docker/files/4459140/launch.txt)

Could you check it?

**Comment by evbauer** [comment]
Hmm, I don't see any error message in the attached txt file. Could you maybe just copy and paste what you see in in your terminal here?

**Comment by evbauer** [comment]
By default, tee only sends standard output to the file. I think you can change that behavior by running this instead to get both standard output and errors in the file:
`./win_home_dockerMESA.sh 2>&1 | tee launch.txt`

**Comment by tokuno-astron** [comment]
Thank you for replying.

After run
' ./win_home_dockerMESA.sh 2>&1 | tee launch.txt ',
I got:
[launch.txt](https://github.com/evbauer/MESA-Docker/files/4459232/launch.txt)

**Comment by tokuno-astron** [comment]
I consider

`Error creating machine`
`Error checking TLS connection`
`Error: No such container: mesa_dock`
`Error response from daemon: Cannot kill container`

as error messages

**Comment by evbauer** [comment]
Thanks. I see the errors now.

I'm not sure I totally understand what's going on yet, but it might help me if you post the output of the following command:
`docker-machine regenerate-certs mesa-machine`

**Comment by tokuno-astron** [comment]
After running following command:
`docker-machine regenerate-certs mesa-machine`
output is below:
`Regenerating TLS certificates`
`Waiting for SSH to be available...`
`Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded`

**Comment by evbauer** [comment]
Oops, I think the machine needs to be started first before running the command. Sorry. Try
`docker-machine start mesa-machine`
`docker-machine regenerate-certs mesa-machine`

**Comment by tokuno-astron** [comment]
OK. Output is below:

`$ docker-machine start mesa-machine`
`Starting "mesa-machine"...`
`(mesa-machine) Check network to re-create if needed...`
`(mesa-machine) Windows might ask for the permission to configure a dhcp server.` `Sometimes, such confirmation window is minimized in the taskbar.`
`(mesa-machine) Waiting for an IP...`
`Machine "mesa-machine" was started.`
`Waiting for SSH to be available...`
`Detecting the provisioner...`
`Started machines may have new IP addresses. You may need to re-run the `docker-machine` `env` command.`

`$ docker-machine regenerate-certs mesa-machine`
`Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y`
`Regenerating TLS certificates`
`Waiting for SSH to be available...`
`Detecting the provisioner...`
`Copying certs to the local machine directory...`
`Copying certs to the remote machine...`
`Setting Docker configuration on the remote daemon...`

**Comment by evbauer** [comment]
That looks good. Now I think it would be good to run this again and see if the output is different:
`./win_home_dockerMESA.sh 2>&1 | tee launch.txt`

**Comment by tokuno-astron** [comment]
After running that code again, I got below:
[launch2.txt](https://github.com/evbauer/MESA-Docker/files/4459618/launch2.txt)
.
It looks like the same as the first errors.

**Comment by evbauer** [comment]
Ok, that at least helps confirm where the issue is. It consistently points to this being the key error:

> Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "tokun")

Unfortunately I don't have a lot of insight into how to solve this particular error. I can't recall having run into it before. Some googling points to a similar discussion that might have some helpful tips: https://github.com/docker/machine/issues/3595#issuecomment-287164286

If you want to try some things and check whether things are working, you should be able to quickly check with these commands:
`docker-machine start mesa-machine`
`docker-machine regenerate-certs mesa-machine`
`eval "$(docker-machine env mesa-machine)"`

If you can get through running those commands without seeing errors, you should be ready to try launching MESA-Docker again. Good luck!

**Comment by tokuno-astron** [comment]
After uninstalling, reinstalling, and some trials, I can get calculations well.
Thank a lot!
