### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by 2sn** [evbauer/MESA-Docker#3]
```shell
docker@db1714077444:~$ cd docker_work/
docker@db1714077444:~/docker_work$ ls
ls: cannot open directory '.': Permission denied
```

**Comment by evbauer** [comment]
Thanks for posting this. I think another user had a similar issue, but I wasn't able to get enough follow up info to diagnose at the time, and I couldn't reproduce it myself.

What OS/version of the script are you using?

**Comment by evbauer** [comment]
Ok, just committed some mounting fixes, so I'm hoping this is resolved now.
