### ISSUE TITLE
Add checks for windows pro/home

### ISSUE THREAD

**Issue by rjfarmer** [evbauer/MESA-Docker#5]
Alot of issues i found when using this with a class of students stemmed from having the wrong docker installed. We (I) should find some way to test inside the git-bash if we are on windows home/pro and give appropriate error messages.

**Comment by rjfarmer** [comment]
It looks like this should work:

if [[ $(wmic os get caption) = *"Home"* ]]
then
echo "Home"
else
echo "Pro"
fi

@evbauer Can you check this works on your windows pro machine?

**Comment by evbauer** [comment]
Good idea. I'll try to check it this evening.

**Comment by evbauer** [comment]
Ok, it looks like that code snippet works great for me. I get "Pro" on my pro machine as desired.
