### ISSUE TITLE
Code detecting a Windows Pro version instead of a Home version

### ISSUE THREAD

**Issue by SachaGR** [evbauer/MESA-Docker#6]
Hi! I was installing MESA by following step by step your guide. I am working with the Windows 10 Home version, so I downloaded Docker Toolbox. 
When I tried to run the win_home_dockerMESA script, I got a warning message saying that I was running windows Pro instead of Windows Home. 
How can I debug that?

Thank you and have a nice day

**Comment by rjfarmer** [comment]
HI, inside the git-bash terminal can you run the command:
>wmic os get caption

and post the output
Thanks

**Comment by SachaGR** [comment]
Hi, the output was:
```
$ wmic os get caption
Caption
Microsoft Windows 10 Famille
```
Windows 10 Famille is the French name of Windows 10 Home.

**Comment by rjfarmer** [comment]
Okay, while i work on fixing the multi lingual support you can just comment out lines 4-8 in the win_home_dockerMESA.sh script to skip the test

**Comment by SachaGR** [comment]
Okay, I skipped the test and now I have another issue:
```
$ ./win_home_dockerMESA.sh
C:\docker
./win_home_dockerMESA.sh: line 64: docker-machine: command not found
./win_home_dockerMESA.sh: line 70: docker-machine: command not found
MESA MACHINE CREATED, stopping for mount point
./win_home_dockerMESA.sh: line 79: docker-machine: command not found

```
I looked into the  "C:\Docker Toolbox" and saw here the "docker" and "docker-machine" applications.
Do you think that the problem could be about the path?

**Comment by rjfarmer** [comment]
can you type:
>which docker-machine

and send the output and also try
> docker-machine ls

Thanks

**Comment by SachaGR** [comment]
I got this: 
```
$ which docker-machine
which: no docker-machine in (/c/Users/Sacha GRELET RIOUT/bin:/mingw32/bin:/usr/l             ocal/bin:/usr/bin:/bin:/mingw32/bin:/usr/bin:/c/Users/Sacha GRELET RIOUT/bin:/c/              Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WIND              OWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowe              rShell/v1.0:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/D              AL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program F              iles (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Inte              l/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Skype/Phone:/              c/Program Files/MATLAB/R2017a/runtime/win64:/c/Program Files/MATLAB/R2017a/bin:/              c/Program Files/nodejs:/c/Program Files/CMake/bin:/c/WINDOWS/System32/OpenSSH:/c              /Program Files/Git/cmd:/c/wamp64/bin/php/php7.1.9/php.exe: C:/Qt/Tools/mingw530_              32/bin:/cmd:/c/Users/Sacha GRELET RIOUT/AppData/Local/Microsoft/WindowsApps:/usr              /bin/vendor_perl:/usr/bin/core_perl)
```
and this:
```
$ docker-machine ls
bash: docker-machine: command not found
```

**Comment by rjfarmer** [comment]
This might work:
> export PATH="/c/Docker Toolbox":$PATH

and then try re-running the win script

**Comment by SachaGR** [comment]
It looks like it worked: the mesa-machine was created and stopped, then I re-ran the win script and now I have a lot of messages like the one below
```
170471275331: Verifying Checksum
170471275331: Download complete
170471275331: Pull complete
```
I guess that I have just to wait for the end of that download.

Thank you for your help and the work you did on this project!

**Comment by SachaGR** [comment]
It tried to start the tutorial but I got this issue: 
```
docker@38eae4f24fd7:~/docker_work/tutorial$ ./mk
gfortran -Wno-uninitialized -fno-range-check -fmax-errors=12  -fprotect-parens -fno-sign-zero -fbacktrace -ggdb -finit-real=snan -fopenmp -fbounds-check -Wuninitialized -Warray-bounds  -ffree-form -x f95-cpp-input -I/home/docker/mesa/include -I/home/docker/mesasdk/include -c ../src/run_star_extras.f
../src/run_star_extras.f:37:32:

       end module run_star_extras
                                1
Fatal Error: Can't open module file 'run_star_extras.mod0' for writing at (1): Permission denied
compilation terminated.
/home/docker/mesa/star/work_standard_makefile:38: recipe for target 'run_star_extras.o' failed
make: *** [run_star_extras.o] Error 1

FAILED
```
I didn't find any solution in the documentation.  Do you know how to fix it? 
(Maybe should I start another issue report, or change the title of this one?)

**Comment by rjfarmer** [comment]
Please make a new issue.

Regarding the previous issue, can you send the output of:
> systeminfo | findstr "Windows:"

Thanks
