### ISSUE TITLE
Windows home check is broken with non-english locals

### ISSUE THREAD

**Issue by rjfarmer** [evbauer/MESA-Docker#7]
See issue #6 

https://stackoverflow.com/questions/52223872/get-windows-version-from-git-bash

**Comment by rjfarmer** [comment]
@evbauer  on your windows pro machine can you look for where bitlocker is installed? If there is say a bitlocker executable? or folder? that way we can check for its existence as the discriminator between home and pro. 

There doesn't seem to be a way to bet the windows type (home vs pro) is language agnostic way

**Comment by evbauer** [comment]
Ok, good idea. I've been traveling, but I'm back now, so I can check on my Windows desktop this evening.

**Comment by evbauer** [comment]
So I think the executable we want is
`/c/Windows/System32/BitLockerWizard.exe`
