### ISSUE TITLE
Error when I try to start the tutorial 

### ISSUE THREAD

**Issue by SachaGR** [evbauer/MESA-Docker#9]
Continuation of the latest messages from #6 

Here is the output of the command
```
$ systeminfo | findstr "Windows:"
Répertoire Windows:                         C:\WINDOWS
```

**Comment by rjfarmer** [comment]
Copying the error message:

> docker@38eae4f24fd7:~/docker_work/tutorial$ ./mk
gfortran -Wno-uninitialized -fno-range-check -fmax-errors=12  -fprotect-parens -fno-sign-zero -fbacktrace -ggdb -finit-real=snan -fopenmp -fbounds-check -Wuninitialized -Warray-bounds  -ffree-form -x f95-cpp-input -I/home/docker/mesa/include -I/home/docker/mesasdk/include -c ../src/run_star_extras.f
../src/run_star_extras.f:37:32:
>
>       end module run_star_extras
>                                1
> Fatal Error: Can't open module file 'run_star_extras.mod0' for writing at (1): Permission denied
compilation terminated.
/home/docker/mesa/star/work_standard_makefile:38: recipe for target 'run_star_extras.o' failed
make: *** [run_star_extras.o] Error 1
> 
> FAILED

@evbauer  any ideas?

**Comment by evbauer** [comment]
I was able to reproduce this by removing write permissions from the make folder before trying to compile:
`sudo chmod 555 make`

That seems to indicate some kind of problem with mounting the `docker_work` directory. But then I don't understand how copying the `tutorial` directory could succeed in the first place.

**Comment by evbauer** [comment]
Ah, I was also able to reproduce by adding `sudo` before the `cp` command. That gives the directory the wrong owner so that the `./mk` command is unable to write and gives the same error.

Did you perhaps do something like this? Were there problems with the normal copy command?

**Comment by evbauer** [comment]
From within the Docker container, please run the following command, and paste the output in this thread
`cd ~/docker_work/tutorial && ls -l`

**Comment by SachaGR** [comment]
Hello! The normal copy command don't start: 
`cp: cannot create directory 'tutorial': Permission denied`
That's why I had to add `sudo` 

Here is the output of the command in the last message: 
```
docker@045cf9603778:~/docker_work$ sudo cp -r $MESA_DIR/star/work tutorial
[sudo] password for docker:
docker@045cf9603778:~/docker_work$ cd ~/docker_work/tutorial && ls -l
total 32
drwxr-xr-x 2 root root   40 Sep 15 14:46 LOGS
-rw-r--r-- 1 root root 2041 Sep 15 14:46 README_first
-rwxr-xr-x 1 root root   19 Sep 15 14:46 clean
-rw-r--r-- 1 root root  656 Sep 15 14:46 inlist
-rw-r--r-- 1 root root  901 Sep 15 14:46 inlist_pgstar
-rw-r--r-- 1 root root  921 Sep 15 14:46 inlist_project
drwxr-xr-x 2 root root   60 Sep 15 14:46 make
-rwxr-xr-x 1 root root  130 Sep 15 14:46 mk
drwxr-xr-x 2 root root   40 Sep 15 14:46 photos
-rwxr-xr-x 1 root root  254 Sep 15 14:46 re
-rwxr-xr-x 1 root root  165 Sep 15 14:46 rn
drwxr-xr-x 2 root root   80 Sep 15 14:46 src

```

**Comment by evbauer** [comment]
Ok, if the `cp` command isn't working, this definitely indicates a problem with mounting the `docker_work` folder.

Given all the problems you had to deal with during the initial setup, the easiest way to deal with this is probably to completely delete the virtual machine and start over. So try this:

`export MACHINE_STORAGE_PATH=C:\\docker`
`docker-machine rm mesa-machine`

Then run the launch script again
`./win_home_dockerMESA.sh`
and let it run all the way through the point where it launches you into the container. This can take a while during the initial run, but it should get you all the way there. You shouldn't have to run the script more than once. Can you get this far? If so, try following the instructions for the tutorial again and see if that goes any better.

**Comment by SachaGR** [comment]
Wow, wait a minute! Should I be in the container now? When I run` ./win_home_dockerMESA.sh` , it asks me for the passwords then a big "MESA DOCKER" appears in the Git Bash window but there is no VM.
Is it normal?

Second question: are `export MACHINE_STORAGE_PATH=C:\\docker` and `docker-machine rm mesa-machine` on the same line? Do you run this command before or after the mesa-machine is started ?

**Comment by SachaGR** [comment]
Is there anything I had to configure in Xming? Or in Docker Toolbox?

**Comment by evbauer** [comment]
Those lines should be run in git bash, but not inside the container. Good question.

I'm not sure what you mean by "I can not run these lines". Can you post the output? The first shouldn't print anything; it just sets an environment variable. You can check that it got set by typing
`echo $MACHINE_STORAGE_PATH`

Once that environment variable is set, you should be able to run the second line to remove the VM. You're right that no separate window pops up for the VM. There is a VM running in the background that your terminal logs into when the script runs properly, but your only interface to it is through the Git Bash window.

I don't think you need to do any configuration for Xming or Docker Toolbox.

**Comment by SachaGR** [comment]
Ok, thank you for the explanations. 

Here is the output of the two lines:
```
docker@020b2b1d826e:~$ export MACHINE_STORAGE_PATH=C:\\docker
docker@020b2b1d826e:~$ echo $MACHINE_STORAGE_PATH
C:\docker
docker@020b2b1d826e:~$ docker-machine rm mesa-machine
-bash: docker-machine: command not found
```

EDIT: I just noticed that I have this warning when I start the mesa-machine 
`/usr/bin/xauth:  file /home/docker/.Xauthority does not exist`

**Comment by evbauer** [comment]
Thanks.

Those commands should be run outside the docker container, before you run `./win_home_dockerMESA.sh`.

The warning about .Xauthority happens for me too. I haven't figured out how to get rid of it, but it doesn't seem to cause any problems, so you can ignore that.

**Comment by SachaGR** [comment]
I deleted the VM and ran the launch script again.
The downloading was successful but then, when I tried to run again `./win_home_dockerMESA.sh` another error appears:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
It seems to be a common issue so I try to solve it and I repost here after that.

**Comment by SachaGR** [comment]
Hi! The VM is created again, I followed the instructions in order to run the tutorial but I have the same issue than rjfarmer reposted in the second comment of this thread. 
I had also to add `sudo` before the `cp` command.

**Comment by evbauer** [comment]
Ah! That's a simple ssh issue that I've run into before. Sorry I forgot about it. Just add this command before you follow the other steps I had you go through before (outside the container):
`sudo rm ~/.ssh/known_hosts`

Then run the other steps to remove the VM so we can start from scratch again.

In addition, let's try to get some more info for me to use in debugging. After you have deleted the VM, instead of running the launch script the usual way, do this instead:
`./win_home_dockerMESA.sh | tee launch_out.txt`

That will run the same script, but also save the terminal output to a text file that we can look through to debug. Once the script has gotten you all the way into the docker container, just type `exit`, then attach the launch_out.txt file here. Thanks!

**Comment by SachaGR** [comment]
Here it is! 
The second one is the second run of the `./win_home_dockerMESA.sh` after the initialization.  
[launch_out.txt](https://github.com/evbauer/MESA-Docker/files/2391156/launch_out.txt)
[launch_out2.txt](https://github.com/evbauer/MESA-Docker/files/2391157/launch_out2.txt)

**Comment by evbauer** [comment]
You shouldn't be running the script twice. It should be able to get all the way through into the docker container just from the initial launch.

When you see "Machine "mesa-machine" was stopped", you still need to wait for it to continue to the next part. Are you killing it when you see that message? That's the step where it mounts the `docker_work` directory, so that would cause the problems you're seeing.

**Comment by SachaGR** [comment]
Oh god...
I re-installed the VM and just waited 10 minutes after the message "Machine "mesa-machine" was stopped"  appeared and then I saw the other messages.

It works perfectly now (I ran the tutorial and everything was ok).

Thank you for your patience and for mesa-docker ! :D

**Comment by evbauer** [comment]
Awesome! Thanks for sticking with it. I'm surprised it took so long to get past that step, so that's good to know for future reference. Maybe I can try to add some sort of warning to let it keep going at that point.
